name: Node CI

on: release

jobs:
  build:
    runs-on: ${{ matrix.os-version }}

    strategy:
      matrix:
        node-version: [12.x]
        os-version: [ubuntu-18.04]

    steps:
      - name: Cancel if not a release publish # workaround has `on` doesn't have this filter
        env:
          ACTION: ${{ github.event.action }}
        run: |
          echo "Invalid release action: $ACTION"
          exit 1
        if: github.event.action != 'published'
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install vsce
        run: npm install -g vsce
      - name: Package extension
        run: |
          tag=${GITHUB_REF#refs/tags/}
          echo "Setting package version $tag"
          npm --no-git-tag-version version "$tag"
          vsce package
      - name: Publish extension to marketplace
        env:
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
        run: |
          vsce publish -p "$AZURE_TOKEN"
