name: Node CI

on: release

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Cancel if not a release publish # workaround has `on` doesn't have this filter
        run: exit 1
        if: github.event.action != 'published'
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: package
        run: |
          tag=${GITHUB_REF#refs/tags/}
          echo "Setting package version $tag"
          npm --no-git-tag-version version "$tag"
          npm install -g vsce
          vsce package
      - name: publish-vsce
        env:
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
        run: |
          git config --global user.email "willis.rh@gmail.com"
          git config --global user.name "Richard Willis"
          vsce publish -p "$AZURE_TOKEN"
