name: Node CI

on: release

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: package
        run: |
          npm install -g vsce
          npm version from-git
          vsce package
      - name: publish-vsce
        env:
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
        run: |
          git config --global user.email "willis.rh@gmail.com"
          git config --global user.name "Richard Willis"
          vsce publish -p $AZURE_TOKEN
      # - name: publish-github
      #   env:
      #     GITHUB_PUSH_TOKEN: ${{ secrets.GITHUB_PUSH_TOKEN }}
      #   run: |
      #     git remote set-url origin "https://badsyntax:$GITHUB_PUSH_TOKEN@github.com/badsyntax/richard-willis-vscode-extension-pack.git"
      #     git push origin HEAD:master
